version: "3.9"

services:

  notebook:
    build: .
    image: ml-astronomic-notebook
    container_name: ml-astronomic_jupyter
    ports:
      - "8888:8888"       # Abre http://localhost:8888 en tu navegador
    volumes:
      - ./outputs:/app/outputs
      - ./models:/app/models
      - ./ml-astronomic.ipynb:/app/ml-astronomic.ipynb
